### ISSUE TITLE
Servlet filter conflict in war-packaged Spring Boot apps

### ISSUE THREAD

**Issue by fmessner** [togglz/togglz#535] opened 2021-03-11 13:14 UTC
Hi,

we're developing a **Spring Boot** application which is **war-packaged** and deployed to a Tomcat (8.5, Java 8). We use Spring Boot auto-configuration from `org.togglz:togglz-spring-boot-starter:2.9.6`. This works fine for our tests which are running in Spring Boot's embedded tomcat. But when deploying to the target tomcat, togglz registers two filters:
 
1. through the Spring Boot `TogglzAutoConfiguration` from `org.togglz:togglz-spring-boot-starter:2.9.6` which registers `HttpServletRequestHolderFilter` (introduced in 2.8.0 with #414).
2. through the web-fragment in `org.togglz:togglz-servlet:2.9.6` which additionally registers `org.togglz.servlet.TogglzFilter` for all requests

The second filter complains then for every(!) request:
```
org.togglz.core.logging.Jdk14LogProvider$Jdk14Log error
SEVERE: Failed to execute RequestListener
java.lang.IllegalStateException: HttpServletRequestHolder.bind() called for a thread that already has a request associated with it. It's likely that the request was not correctly removed from the thread before it is put back into the thread pool.
        at org.togglz.servlet.util.HttpServletRequestHolder.bind(HttpServletRequestHolder.java:22)
        at org.togglz.servlet.util.HttpServletRequestHolderListener.begin(HttpServletRequestHolderListener.java:25)
        at org.togglz.servlet.CompositeRequestListener.begin(CompositeRequestListener.java:36)
        at org.togglz.servlet.TogglzFilter.doFilter(TogglzFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
```
Since the rest of our application is bootstrapped with Spring Boot auto-configuration we'd like to keep that one and prevent the web-fragment from being registered. The only way we were able to suppress the togglz web-fragment but keep the one to trigger Spring initialization was to introduce a `web.xml` with just this element :

```xml
    <absolute-ordering>
        <name>spring_web</name>
    </absolute-ordering>
```

It would be very helpful if there was more control over the way togglz is registered in classic servlet containers since having to white-list the web-fragments might easily produce unexpected behaviour.

**Comment by bennetelli** [comment] 2021-03-15 09:57
Hey @fmessner I'm able to reproduce your issue. Sorry for that :-( When removing the RequestHolderFilterConfiguration from togglz-spring-boot-starter everything works as expected. I think a ConditionalOnProperty would be helpful to disable the RequestHolderFilterConfiguration if necessary.

Would this be a solution you could work with?

**Comment by bennetelli** [comment] 2021-03-15 12:47
see #537

**Comment by bennetelli** [comment] 2021-03-15 13:05
hey @fmessner and @huehnerlady,

I just opened a PR #537 to fix @fmessner's issue. As it affects both of your use-cases I would like to discuss it with you. 
Should the togglz.web.request-holder-filter property be true or false by default? What's your opinion about it?

see #414

**Comment by bennetelli** [comment] 2021-03-16 07:52
I guess the default should be true. That's the status quo in the latest release. Probably most of the togglz user will use togglz with jar packaging instead of war. Would you be fine with having it on true by default @fmessner ? You would have to disable it in the application.properties file while all the other users wouldn't have to touch their code.

**Comment by fmessner** [comment] 2021-03-16 08:26
Hey @bennetelli,

many thanks for your quick fix! And I agree, I think the runtime for Spring Boot is in most cases the embedded tomcat and so I'd suggest to set the default to `true` and we'll just use the opt-out then.

I have some questions regarding the current solution:
1. Could it happen that we're bootstrapping the `FeatureManager` with the Spring Boot auto-configuration and another FeatureManager is bootstrapped by the TogglzFilter?
2. Is the order of the initialization (Spring Boot / Togglz) deterministic? From the Servlet spec I guess no unless we use the `<absolute-ordering>`-element ...
3. Should we introduce a web.xml just to set the `org.togglz.FEATURE_MANAGER_PROVIDED=true` then?

For our scenario, I still think it would be better to leave the initialization of the togglz beans to Spring Boot and not use the web-fragment at all. Would it be possible to offer any means to prevent the loading of the web-fragment (e.g. a togglz-servlet.jar-variant without the web-fragment for Spring Boot users)?

**Comment by huehnerlady** [comment] 2021-03-16 10:55
@bennetelli I would not say that just because 'true' would not break anything this is the right value for it. If that is the right value, then that is good, if not, I would say it needs to get into a major release and then that is also fine.

More important I find the last part. If the vast majority is using spring boot, then that should be the default in my opinion.

But I would like to step back a moment and ask: Why are there 2 filters? Maybe the auto-configuration of the requestFilter is wrong and it should be `@ConditionalOnMissingBean(TogglzFilter.class)`? Why can there not be more than one TogglzFilter be registered, as they might do different things?? 
If that is ok with you and it is not holding you up too much I would like to have a look a bit deeper into this, which I hope I can achieve tomorrow or Friday.

Or if you have another look into it, maybe you can find the answer to my question?

**Comment by fmessner** [comment] 2021-03-16 13:54
@huehnerlady the current conflict arises since both filters at the moment try to store the current request to a ThreadLocal via `HttpServletRequestHolder.bind(request)`. While this is the only purpose of your `HttpServletRequestHolderFilter`, the `TogglzFilter` additionally bootstraps the FeatureManager which is something we want to leave to the Spring Boot mechanics anyway.

**Comment by huehnerlady** [comment] 2021-03-16 13:58
ok, so you are saying you do not just want to resolve the conflict but not have the other Filter at all?

**Comment by fmessner** [comment] 2021-03-16 14:26
Yes.

For Spring Boot running in the embedded tomcat, the `TogglzFilter` is not registered at all. With this setup we're doing some local testing which works perfectly without that filter. The registration happens only when we're deploying to tomcat and the web-fragment is loaded. Since the `TogglzFilter` and the `HttpServletRequestHolderFilter` are both binding request to the ThreadLocal and the bootstrapping which is done in addition is not needed we would like to get rid of the web-fragment stuff completely.

**Comment by huehnerlady** [comment] 2021-03-16 14:58
@fmessner thanks for the quick response.

That is fine by me then. As I say happy for the default to be whatever makes more sense, if it is false it should be released under a major version.

I would then unsubscribe here and let you do your thing, if you need more information from me, please mention me agagin :)

**Comment by fmessner** [comment] 2021-03-24 07:46
Hi @bennetelli,

just wanted to ask if you found the time to think about my questions in  https://github.com/togglz/togglz/issues/535#issuecomment-800059047.

Does it sound reasonable to you that we'd prefer to suppress the web-fragment in favour of a complete Spring Boot configuration? And are there any chances this could be done?

**Comment by bennetelli** [comment] 2021-04-13 15:53
hey @fmessner sorry for my late response. I was in vacation and started a new job at the beginning of April. 

You will get a detailed response tomorrow morning.

**Comment by bennetelli** [comment] 2021-04-23 12:31
I just release 2.9.7 which contains the fix. Would be great if you could give me feedback.

**Comment by bennetelli** [comment] 2021-06-01 06:33
As I didn't get a respose, I would like to close this issue.

**Closed by bennetelli** 2021-06-01 06:33 UTC
