### ISSUE TITLE
Spring Boot admin console no longer working on spring-boot 1.5.1.RELEASE

### ISSUE THREAD

**Issue by bmusazay** [togglz/togglz#202] opened 2017-02-03 23:05 UTC
Seems like org.springframework.boot.context.embedded.ServletRegistrationBean is no longer included in the latest spring boot release, which the console depends on.

**Comment by chkal** [comment] 2017-02-04 10:19
This issue is currently discussed in #201

**Comment by marceloverdijk** [comment] 2017-02-04 15:21
Duplicate of #201.

**Closed by marceloverdijk** 2017-02-04 15:21 UTC
