### ISSUE TITLE
<name> Tag in 2.4.0 togglz-console causes validation error in Weblogic 12.2.1

### ISSUE THREAD

**Issue by pvolkemer** [togglz/togglz#204] opened 2017-03-06 07:27 UTC
I tried to include togglz 2.4.0 in a Java EE 7 application running on Weblogic 12.2.1.

Upon deployment an error occurs:

```
[ERROR] Failed to execute goal com.oracle.weblogic:weblogic-maven-plugin:12.2.1-0-0:redeploy (wls-redeploy) on project foobar: weblogic.Deployer$DeployerException: weblogic.deploy.api.tools.deployer.DeployerException: Task 4 failed: [Deployer:149026]deploy application foobar on foobarcluster.
[ERROR] Target state: redeploy failed on Cluster foobarcluster
[ERROR] weblogic.descriptor.DescriptorException: VALIDATION PROBLEMS WERE FOUND
[ERROR] <path_to_basedomain>\base_domain\weblogic.utils.classloaders.GenericClassLoader@26f37eff finder: weblogic.utils.classloaders.CodeGenClassFinder@70f09e70 annotation: foobar@\WEB-INF\lib\togglz-console-2.4.0.Final.jar!\META-INF\web-fragment.xml:6:26:6:26: problem: cvc-datatype-valid.1.1: string value 'togglz-console' does not match pattern for java-identifierType in namespace http://java.sun.com/xml/ns/javaee
```

Going back to version 2.3.0 works since the <name> Tag seems to have been added in version 2.4.0.
Is there anything you can do about this or is this an issue with Oracle?

See also my question on SO: http://stackoverflow.com/questions/42580361/togglz-console-included-in-java-ee7-application-running-on-weblogic-12-2-1-0

**Comment by chkal** [comment] 2017-03-06 09:33
I just committed a fix for this issue. Any change that you could try the latest snapshots? They should be deployed within the next 30 minutes.

See this page for details: https://www.togglz.org/download.html

**Comment by pvolkemer** [comment] 2017-03-06 09:38
Shouldn't be a problem sometime today. I'll let you know the results.

**Comment by chkal** [comment] 2017-03-06 09:52
Ok, great! Thanks!

**Comment by pvolkemer** [comment] 2017-03-06 11:55
I was just able to confirm that togglz-console 2.5.0-SNAPSHOT deploys on Weblogic 12.2.1 like a charm!
![image](https://cloud.githubusercontent.com/assets/7250873/23608971/209c93e4-026c-11e7-806e-c1233f5aace4.png)

**Comment by chkal** [comment] 2017-03-06 12:08
Awesome! Great! 

I guess we will push out 2.4.1.Final in the next days to address this and another issue.

Thanks a lot for reporting this.

**Closed by chkal** 2017-03-06 12:08 UTC

**Comment by akkiJoshi** [comment] 2018-08-23 06:16
Hi pvolkemer,
I am also using the togglz with Weblogic server and I followed every step but togglz console is not getting launched. I am getting "Error 403--Forbidden" error.
I can see the war is there and deployed in weblogic console.

![image](https://user-images.githubusercontent.com/9669173/44507879-d9f2b780-a6c9-11e8-895e-6050000486f3.png)


Can you please share the steps that you followed, may be i missed something somewhere. 
And if you also encountered the same problem, please share the resolution also.

Thanks 
Aakash Joshi

**Comment by ruifigueira** [comment] 2018-08-23 08:53
That `403 Forbidden` is due to lack of authentication. See  the [Admin Console documentation](https://www.togglz.org/documentation/admin-console.html) for more details on how to configure it:

> Please note that you will have to configure the user authentication as described in the [Configuration](https://www.togglz.org/documentation/configuration.html) and [Authentication](https://www.togglz.org/documentation/authentication.html) chapters to be able to access the admin console.

**Comment by ruifigueira** [comment] 2018-08-23 13:46
With that specific custom `UserProvider`, you'll need to somehow ensure a `username=admin` attribute exists in the `HttpServletRequest`, otherwise it will deny the access.

Did you try something simpler? For instance:

```
 @Override
 public FeatureUser getCurrentUser() {
    return new SimpleFeatureUser("admin", true);
}
```

**Comment by akkiJoshi** [comment] 2018-08-24 12:26
i have tried it and now console is able to get launched. But getting below exception when changing the status of the feature.
![image](https://user-images.githubusercontent.com/9669173/44584475-ab0e3b80-a7c6-11e8-9209-ed5efccc2f65.png)


**Exception :-**

Error 500--Internal Server Error
--

java.lang.IllegalStateException: Failed to write new values 	at org.togglz.core.repository.file.ReloadablePropertiesFile.write(ReloadablePropertiesFile.java:117) 	at org.togglz.core.repository.file.ReloadablePropertiesFile.access$100(ReloadablePropertiesFile.java:23) 	at org.togglz.core.repository.file.ReloadablePropertiesFile$PropertyFileEditor.commit(ReloadablePropertiesFile.java:153) 	at org.togglz.core.repository.property.PropertyBasedStateRepository.setFeatureState(PropertyBasedStateRepository.java:122) 	at org.togglz.core.manager.DefaultFeatureManager.setFeatureState(DefaultFeatureManager.java:109) 	at org.togglz.core.manager.LazyResolvingFeatureManager.setFeatureState(LazyResolvingFeatureManager.java:59) 	at org.togglz.console.handlers.edit.EditPageHandler.process(EditPageHandler.java:78) 	at org.togglz.console.TogglzConsoleServlet.service(TogglzConsoleServlet.java:63) 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:844) 	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:280) 	at weblogic.servlet.internal.StubSecurityHelper$ServletServiceAction.run(StubSecurityHelper.java:254) 	at weblogic.servlet.internal.StubSecurityHelper.invokeServlet(StubSecurityHelper.java:136) 	at weblogic.servlet.internal.ServletStubImpl.execute(ServletStubImpl.java:341) 	at weblogic.servlet.internal.TailFilter.doFilter(TailFilter.java:25) 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79) 	at org.togglz.servlet.TogglzFilter.doFilter(TogglzFilter.java:100) 	at weblogic.servlet.internal.FilterChainImpl.doFilter(FilterChainImpl.java:79) 	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.wrapRun(WebAppServletContext.java:3367) 	at weblogic.servlet.internal.WebAppServletContext$ServletInvocationAction.run(WebAppServletContext.java:3333) 	at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:321) 	at weblogic.security.service.SecurityManager.runAs(SecurityManager.java:120) 	at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:57) 	at weblogic.servlet.internal.WebAppServletContext.doSecuredExecute(WebAppServletContext.java:2220) 	at weblogic.servlet.internal.WebAppServletContext.securedExecute(WebAppServletContext.java:2146) 	at weblogic.servlet.internal.WebAppServletContext.execute(WebAppServletContext.java:2124) 	at weblogic.servlet.internal.ServletRequestImpl.run(ServletRequestImpl.java:1564) 	at weblogic.servlet.provider.ContainerSupportProviderImpl$WlsRequestExecutor.run(ContainerSupportProviderImpl.java:254) 	at weblogic.work.ExecuteThread.execute(ExecuteThread.java:295) 	at weblogic.work.ExecuteThread.run(ExecuteThread.java:254) Caused by: java.io.FileNotFoundException: /features.properties (Permission denied) 	at java.io.FileOutputStream.open(Native Method) 	at java.io.FileOutputStream.(FileOutputStream.java:221) 	at java.io.FileOutputStream.(FileOutputStream.java:171) 	at org.togglz.core.repository.file.ReloadablePropertiesFile.write(ReloadablePropertiesFile.java:111) 	... 28 more
--


**In Weblogic the exception stacktrace :**

<Aug 24, 2018 5:54:55 PM IST> <Error> <HTTP> <BEA-101020> <[ServletContext@1530826218[app:OmsServer_omsserver_weblogic module:/togglz path:null spec-version:3.0]] Servlet failed w
ith an Exception
java.lang.IllegalStateException: Failed to write new values
        at org.togglz.core.repository.file.ReloadablePropertiesFile.write(ReloadablePropertiesFile.java:117)
        at org.togglz.core.repository.file.ReloadablePropertiesFile.access$100(ReloadablePropertiesFile.java:23)
        at org.togglz.core.repository.file.ReloadablePropertiesFile$PropertyFileEditor.commit(ReloadablePropertiesFile.java:153)
        at org.togglz.core.repository.property.PropertyBasedStateRepository.setFeatureState(PropertyBasedStateRepository.java:122)
        at org.togglz.core.manager.DefaultFeatureManager.setFeatureState(DefaultFeatureManager.java:109)
        Truncated. see log file for complete stacktrace
Caused By: java.io.FileNotFoundException: /features.properties (Permission denied)
        at java.io.FileOutputStream.open(Native Method)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:221)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
        at org.togglz.core.repository.file.ReloadablePropertiesFile.write(ReloadablePropertiesFile.java:111)
        at org.togglz.core.repository.file.ReloadablePropertiesFile.access$100(ReloadablePropertiesFile.java:23)
        Truncated. see log file for complete stacktrace

**Comment by ruifigueira** [comment] 2018-08-24 14:38
You don't have permissions on the `/features.properties` file.

```
Caused By: java.io.FileNotFoundException: /features.properties (Permission denied)
```

These problems are not really related to Weblogic or this ticket. You can use https://gitter.im/togglz/togglz if you have any problems or doubts.
